name: "Build Version"
description: "Generate a date based build version"
inputs:
  path:
    description: "Path of package.json"
    default: "./"
    required: false
  separator:
    description: "Separates product version from build number"
    default: "-"
    required: false
outputs:
  version:
    description: "The generated build version"
runs:
  using: "node12"
  main: "dist/index.js"
